'use client';
import { useMemo, useState } from 'react';
import { saltState } from '../data/salt_reconstruction_v0_1';
const tabs=['OVERVIEW','EVIDENCE','EVENTS','GRAPH','LEDGERS','PULSE','NEXT SCOUT'];
export default function Page(){
 const [activeTab,setActiveTab]=useState('OVERVIEW'); const [selected,setSelected]=useState(null);
 const acceptedFlows=useMemo(()=>saltState.flows.filter(f=>f.status==='ACCEPTED'),[]);
 const highPriority=saltState.nextScout.filter(x=>x.priority==='HIGH').length;
 return <main className="console">
  <header className="topbar"><div className="brandBlock"><div className="brandMark">A</div><div><div className="brand">ALAGBARA</div><div className="title">{saltState.title} <span>— {saltState.version}</span></div><div className="subtitle">REAL EVIDENCE → GRAPH → PULSE → NEXT SCOUT</div></div></div><div className="topMeta"><span>{saltState.asOf} · WAT</span><b className="statusPill">● KERNEL TESTED / PASS</b></div></header>
  <nav className="tabs">{tabs.map(tab=><button key={tab} className={activeTab===tab?'tab active':'tab'} onClick={()=>setActiveTab(tab)}>{tab}</button>)}</nav>
  <section className="workspace">
   <aside className="rail leftRail"><SectionTitle eyebrow="RECONSTRUCTION PIPELINE" title="Evidence → Pulse"/>{[['01','Evidence Passport','Source · provenance · raw record','EVIDENCE'],['02','Trade Event','Normalized observation','EVENTS'],['03','Graph Proposal','Subject · relation · evidence','GRAPH'],['04','Validation Engine','Accepted · Unknown · Contradicted','LEDGERS'],['05','Canonical Graph','Accepted propositions only','GRAPH'],['06','Salt Trade Pulse','Current state snapshot','PULSE'],['07','Next Scout','Targeted evidence acquisition','NEXT SCOUT']].map(([n,t,d,target],i)=><button key={n} className={'pipelineStep '+(i===4?'selectedStep':'')} onClick={()=>setActiveTab(target)}><span className="stepNo">{n}</span><span><strong>{t}</strong><small>{d}</small></span></button>)}</aside>
   <section className="center">
    <div className="heroHead"><div><div className="eyebrow">TRADE WORLD · OBSERVED FLOWS</div><h1>SALT REAL WORLD</h1><p>Aggregate trade flows and transaction evidence are deliberately separated.</p></div><div className="scope"><span>FOCUS</span><b>West Africa</b><span>PRODUCT</span><b>Salt · HS 250100</b><span>DATA PERIOD</span><b>2024</b></div></div>
    <div className="flowPlane"><div className="legend"><span className="dot aggregate"></span> Aggregate evidence <span className="dot transaction"></span> Transaction evidence <span className="dot unknown"></span> Unknown</div>
     <div className="beninCore" onClick={()=>setSelected({kind:'graph',title:'BENIN',data:{type:'canonical anchor',status:'ACCEPTED'}})}><span>BENIN</span><small>CANONICAL ANCHOR</small></div>
     <div className="flowLines">{saltState.flows.map((f,i)=><button key={f.id} className={'flowCard flow'+i} onClick={()=>setSelected({kind:'flow',title:f.source+' → '+f.destination,data:f})}><span className="flag">{flagFor(f.source)}</span><div><strong>{f.source} → {f.destination}</strong><b>{f.quantity}</b><small>{f.sourceLabel}</small></div>{f.status==='CONTRADICTED'&&<em>quantity conflict</em>}</button>)}</div>
     <div className="transactionStrip">{saltState.events.map(e=><button key={e.id} className="transactionCard" onClick={()=>setSelected({kind:'event',title:e.id,data:e})}><span className="eventBadge">TX</span><div><strong>{e.exporter} → {e.importer}</strong><b>{e.quantity}</b><small>{e.date} · {e.source} · {e.packaging}</small></div><em>UNKNOWN</em></button>)}</div>
     <div className="graphDeck"><div className="deckLabel">CANONICAL GRAPH <small>SOURCE-VALIDATED PROPOSITIONS</small></div><div className="graphNodes">{acceptedFlows.map(f=><button key={f.id} className="node" onClick={()=>setSelected({kind:'graph',title:f.source+' → BENIN',data:f})}><i></i><span>{f.source}</span><b>{f.quantity}</b><small>WITS / 2024</small></button>)}<button className="node beninNode" onClick={()=>setSelected({kind:'graph',title:'BENIN',data:{acceptedEdges:acceptedFlows.length}})}><i></i><span>BENIN</span><b>{acceptedFlows.length} edges</b><small>accepted</small></button></div></div>
    </div>
    <div className="pulseBar"><div className="pulseHeader"><span>SALT PULSE v0.1</span><small>CURRENT STATE · AS OF {saltState.asOf}</small></div><div className="metrics"><Metric value={acceptedFlows.length} label="Accepted trade edges"/><Metric value={saltState.events.length} label="Transaction events observed"/><Metric value={saltState.unknowns.length+'+'} label="Key unknowns"/><Metric value={saltState.contradictions.length} label="Contradiction" danger/></div></div>
    <div className="nextScout"><div className="sectionHeader"><div><span className="eyebrow">PRIORITISED EVIDENCE ACQUISITION</span><h2>NEXT SCOUT</h2></div><b>{highPriority} HIGH PRIORITY</b></div><div className="scoutGrid">{saltState.nextScout.map(item=><button key={item.id} className="scoutCard" onClick={()=>setSelected({kind:'scout',title:item.id,data:item})}><div className="scoutNo">{item.id.replace('SCOUT-','')}</div><div><strong>{item.title}</strong><p>{item.question}</p><small>TARGET · {item.target}</small></div><span className={'priority '+item.priority.toLowerCase()}>{item.priority}</span></button>)}</div></div>
   </section>
   <aside className="rail rightRail"><SectionTitle eyebrow="EPISTEMIC STATE" title="Ledgers"/><Ledger title="UNKNOWN LEDGER" tone="unknown" items={saltState.unknowns} onSelect={setSelected}/><Ledger title="CONTRADICTION LEDGER" tone="danger" items={saltState.contradictions} onSelect={setSelected}/><div className="integrityCard"><span>INTEGRITY RULE</span><strong>UNKNOWN ≠ FALSE</strong><p>Contradictions remain open until new evidence resolves them.</p></div></aside>
  </section>
  {selected&&<DetailDrawer selected={selected} onClose={()=>setSelected(null)}/>}
 </main>;
}
function SectionTitle({eyebrow,title}){return <div className="sectionTitle"><span>{eyebrow}</span><h2>{title}</h2></div>}
function Metric({value,label,danger}){return <div className={danger?'metric dangerMetric':'metric'}><b>{value}</b><span>{label}</span></div>}
function Ledger({title,tone,items,onSelect}){return <section className={'ledger '+tone}><div className="ledgerHead"><span>{title}</span><b>{items.length}</b></div>{items.map(item=><button key={item.id} onClick={()=>onSelect({kind:tone,title:item.id,data:item})}><span className="q">?</span><div><strong>{item.field||item.subject}</strong><small>{item.reason||item.attribute}</small></div></button>)}</section>}
function DetailDrawer({selected,onClose}){const d=selected.data||{};return <div className="drawerBackdrop" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><span className="eyebrow">{selected.kind.toUpperCase()}</span><h2>{selected.title}</h2><div className="drawerBody">{Object.entries(d).map(([k,v])=><div className="detailRow" key={k}><span>{humanize(k)}</span><strong>{typeof v==='object'?JSON.stringify(v):String(v)}</strong></div>)}</div>{selected.kind==='event'&&<div className="trace"><b>EPISTEMIC TRACE</b><span>EvidencePassport</span><i>↓</i><span>TradeEvent</span><i>↓</i><span>GraphProposal</span><i>↓</i><span>Validation</span></div>}</aside></div>}
function humanize(k){return k.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,x=>x.toUpperCase())}
function flagFor(country){return ({GHANA:'🇬🇭',SENEGAL:'🇸🇳',EGYPT:'🇪🇬',INDIA:'🇮🇳'})[country]||'•'}
