alter table public.alagbara_cases
  add column vision text,
  add column current_state text,
  add column sovereignty_outcome jsonb,
  drop column next_action;

comment on column public.alagbara_cases.vision is 'Human-supplied: the long-term aim this case serves. Never generated by the model.';
comment on column public.alagbara_cases.current_state is 'Human-supplied: where things stand now. Never generated by the model.';
comment on column public.alagbara_cases.sovereignty_outcome is 'Reflective, human-authored: {capability_gained, control_gained, dependency_reduced, resilience_gained, strategic_freedom_gained, evidence}. Logged alongside result, not generated by ALAGBARA.';
